### PR TITLE
Shortcut to open the trade window

### PR DESCRIPTION
**Pull request by JonHinkerton**
Adds a button in the Bag of Tricks tab to give a shortcut to open the trade window which you basically made on discord anyway.

### CODE REVIEW

**Comment by xADDBx** [comment]
1. Did you try whether it works?
2. I think this might need a check on whether you are on Starship/Ground? It's possible that when you're on the global map or in a spaceship (or in combat?), this could cause issues...

**Comment by xADDBx** [comment]
3. Close the UMM GUI automatically if the button is pressed?

**Comment by xADDBx** [comment]
Is there anything you'd like to change? I'll create a new release in the next few days so I'll probably merge before then

**Comment by JonHinkerton** [comment]
Hold off on this for now. I’m still working on the problem with using it away from the bridge. Made some progress today getting to the vendor info and loading it in my function, still need to look into why the conditionals fail next.

**Comment by xADDBx** [comment]
Okay; If you want it in the very next version, you'll likely have around 2 days; though it wouldn't be an issue to release another version for this, so you can take your time;

**Comment by xADDBx** [comment]
Is there a reason for closing this?

**Comment by JonHinkerton** [comment]
It’s pretty far from working as desired. I assume anything that does work will not resemble this commit at all.

**Pull request closed without merging**
